### ISSUE TITLE
Error while collecting the data

### ISSUE THREAD

**Issue by SExpert12** [HemuManju/carla-data-collector#2]
Hi, 
This is how I collect the data. I build the CARLA from source and I start with 'make launch'. Then I run the 'collect.py ' on second terminal. As soon as I run the 'collect.py', I got this:

make: *** [Util/BuildTools/Linux.mk:7: launch] Killed on server terminal

and this on client side:

Waiting for server to be ready: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:26769, attempt 25 of 25
 Waiting for server to be ready: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to localhost:31442, attempt 25 of 25
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryzen/Downloads/carla-data-collector/modules/data_collector.py", line 186, in single_instance_collector
    data_collector = DataCollector(self.cfg, self.write_path)
  File "/home/ryzen/Downloads/carla-data-collector/modules/data_collector.py", line 99, in __init__
    self.server = CarlaServer(config=self.cfg)
  File "/home/ryzen/Downloads/carla-data-collector/modules/carla_server.py", line 17, in __init__
    self.core = CarlaCore(self.cfg['carla_server'])
  File "/home/ryzen/Downloads/carla-data-collector/core/carla_core.py", line 75, in __init__
    self.connect_client()
  File "/home/ryzen/Downloads/carla-data-collector/core/carla_core.py", line 149, in connect_client
    raise Exception(
Exception: Cannot connect to server. Try increasing 'timeout' or 'retries_on_error' at the carla configuration
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryzen/Downloads/carla-data-collector/modules/data_collector.py", line 186, in single_instance_collector
    data_collector = DataCollector(self.cfg, self.write_path)
  File "/home/ryzen/Downloads/carla-data-collector/modules/data_collector.py", line 99, in __init__
    self.server = CarlaServer(config=self.cfg)
  File "/home/ryzen/Downloads/carla-data-collector/modules/carla_server.py", line 17, in __init__
    self.core = CarlaCore(self.cfg['carla_server'])
  File "/home/ryzen/Downloads/carla-data-collector/core/carla_core.py", line 75, in __init__
    self.connect_client()
  File "/home/ryzen/Downloads/carla-data-collector/core/carla_core.py", line 149, in connect_client
    raise Exception(
Exception: Cannot connect to server. Try increasing 'timeout' or 'retries_on_error' at the carla configuration
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryzen/Downloads/carla-data-collector/modules/data_collector.py", line 186, in single_instance_collector
    data_collector = DataCollector(self.cfg, self.write_path)
  File "/home/ryzen/Downloads/carla-data-collector/modules/data_collector.py", line 99, in __init__
    self.server = CarlaServer(config=self.cfg)
  File "/home/ryzen/Downloads/carla-data-collector/modules/carla_server.py", line 17, in __init__
    self.core = CarlaCore(self.cfg['carla_server'])
  File "/home/ryzen/Downloads/carla-data-collector/core/carla_core.py", line 75, in __init__
    self.connect_client()
  File "/home/ryzen/Downloads/carla-data-collector/core/carla_core.py", line 149, in connect_client
    raise Exception(
Exception: Cannot connect to server. Try increasing 'timeout' or 'retries_on_error' at the carla configuration
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryzen/Downloads/carla-data-collector/modules/data_collector.py", line 186, in single_instance_collector
    data_collector = DataCollector(self.cfg, self.write_path)
  File "/home/ryzen/Downloads/carla-data-collector/modules/data_collector.py", line 99, in __init__
    self.server = CarlaServer(config=self.cfg)
  File "/home/ryzen/Downloads/carla-data-collector/modules/carla_server.py", line 17, in __init__
    self.core = CarlaCore(self.cfg['carla_server'])
  File "/home/ryzen/Downloads/carla-data-collector/core/carla_core.py", line 75, in __init__
    self.connect_client()
  File "/home/ryzen/Downloads/carla-data-collector/core/carla_core.py", line 149, in connect_client
    raise Exception(
Exception: Cannot connect to server. Try increasing 'timeout' or 'retries_on_error' at the carla configuration

**Comment by HemuManju** [comment]
@SExpert12, there is a `carla_path` variable in [experiment_config.yaml](https://github.com/HemuManju/carla-data-collector/blob/cc692dc7de3fad0a2d06b213b1ca67ecdc80ff12/experiment_config.yaml#L13C3-L13C13) config file. Please set the correct path and rerun the `collect.py`

**Comment by SExpert12** [comment]
Okay. Thanks
